require('plugins.lazy-nvim')
require('plugins.luasnip')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.nvim-cmp')
require('plugins.gitsings')
require('plugins.telescope')
